# Language code specification: https://www.w3.org/International/articles/language-tags/
# Exclusion:
# - EN
# - SC -> TC
# - Regional
# - CJK Regional
# - Glyphs
# - Symbols
# - Numbers
# - Pure Katakana and Hiragana
# - Others
dataset:
  path: ./dataset/fonts
  exclusion: []
  specs:
    - path:
        - .
      rule: |
        lambda x: \
          x.split('/')[-1].split('\\')[-1] in [
            'AvenirNext.ttc',
            'Denton-Light.otf',
            'Inter_28pt-Medium.ttf',
            'Keyboard.ttf',
            'Merriweather_36pt-Medium.ttf'
          ]
      language: en
