# Language code specification: https://www.w3.org/International/articles/language-tags/
# Exclusion:
# - EN
# - SC -> TC
# - Regional
# - CJK Regional
# - Glyphs
# - Symbols
# - Numbers
# - Pure Katakana and Hiragana
# - Others
dataset:
  path: ./dataset/fonts
  exclusion: []
  specs:
    - path:
        - .
      rule: |
        lambda x: \
          x.split('/')[-1].split('\\')[-1] in [
            'AlfaSlabOne-Regular.ttf',
            'Arvo-Bold.ttf',
            'Arvo-BoldItalic.ttf',
            'Arvo-Italic.ttf',
            'Arvo-Regular.ttf',
            'Bitter-Italic-VariableFont_wght.ttf',
            'Bitter-VariableFont_wght.ttf',
            'CormorantGaramond-Bold.ttf',
            'CormorantGaramond-BoldItalic.ttf',
            'CormorantGaramond-Italic-VariableFont_wght.ttf',
            'CormorantGaramond-Italic.ttf',
            'CormorantGaramond-Light.ttf',
            'CormorantGaramond-LightItalic.ttf',
            'CormorantGaramond-Medium.ttf',
            'CormorantGaramond-MediumItalic.ttf',
            'CormorantGaramond-Regular.ttf',
            'CormorantGaramond-SemiBold.ttf',
            'CormorantGaramond-SemiBoldItalic.ttf',
            'CormorantGaramond-VariableFont_wght.ttf',
            'CrimsonText-Bold.ttf',
            'CrimsonText-BoldItalic.ttf',
            'CrimsonText-Italic.ttf',
            'CrimsonText-Regular.ttf',
            'CrimsonText-SemiBold.ttf',
            'CrimsonText-SemiBoldItalic.ttf',
            'Denton-Light.otf',
            'EBGaramond-Italic-VariableFont_wght.ttf',
            'EBGaramond-VariableFont_wght.ttf',
            'IBMPlexSerif-Bold.ttf',
            'IBMPlexSerif-BoldItalic.ttf',
            'IBMPlexSerif-ExtraLight.ttf',
            'IBMPlexSerif-ExtraLightItalic.ttf',
            'IBMPlexSerif-Italic.ttf',
            'IBMPlexSerif-Light.ttf',
            'IBMPlexSerif-LightItalic.ttf',
            'IBMPlexSerif-Medium.ttf',
            'IBMPlexSerif-MediumItalic.ttf',
            'IBMPlexSerif-Regular.ttf',
            'IBMPlexSerif-SemiBold.ttf',
            'IBMPlexSerif-SemiBoldItalic.ttf',
            'IBMPlexSerif-Thin.ttf',
            'IBMPlexSerif-ThinItalic.ttf',
            'Inter_28pt-Black.ttf',
            'Inter_28pt-BlackItalic.ttf',
            'Inter_28pt-Bold.ttf',
            'Inter_28pt-BoldItalic.ttf',
            'Inter_28pt-ExtraBold.ttf',
            'Inter_28pt-ExtraBoldItalic.ttf',
            'Inter_28pt-ExtraLight.ttf',
            'Inter_28pt-ExtraLightItalic.ttf',
            'Inter_28pt-Italic.ttf',
            'Inter_28pt-Light.ttf',
            'Inter_28pt-LightItalic.ttf',
            'Inter_28pt-Medium.ttf',
            'Inter_28pt-MediumItalic.ttf',
            'Inter_28pt-Regular.ttf',
            'Inter_28pt-SemiBold.ttf',
            'Inter_28pt-SemiBoldItalic.ttf',
            'Inter_28pt-Thin.ttf',
            'Inter_28pt-ThinItalic.ttf',
            'Inter-Italic-VariableFont_opsz,wght.ttf',
            'Inter-VariableFont_opsz,wght.ttf',
            'Lato-Black.ttf',
            'Lato-BlackItalic.ttf',
            'Lato-Bold.ttf',
            'Lato-BoldItalic.ttf',
            'Lato-Italic.ttf',
            'Lato-Light.ttf',
            'Lato-LightItalic.ttf',
            'Lato-Regular.ttf',
            'Lato-Thin.ttf',
            'Lato-ThinItalic.ttf',
            'LibreBaskerville-Bold.ttf',
            'LibreBaskerville-Italic.ttf',
            'LibreBaskerville-Regular.ttf',
            'Lora-Bold.ttf',
            'Lora-BoldItalic.ttf',
            'Lora-Italic-VariableFont_wght.ttf',
            'Lora-Italic.ttf',
            'Lora-Medium.ttf',
            'Lora-MediumItalic.ttf',
            'Lora-Regular.ttf',
            'Lora-SemiBold.ttf',
            'Lora-SemiBoldItalic.ttf',
            'Lora-VariableFont_wght.ttf',
            'Merriweather_24pt_SemiCondensed-Black.ttf',
            'Merriweather_24pt_SemiCondensed-BlackItalic.ttf',
            'Merriweather_24pt_SemiCondensed-Bold.ttf',
            'Merriweather_24pt_SemiCondensed-BoldItalic.ttf',
            'Merriweather_24pt_SemiCondensed-ExtraBold.ttf',
            'Merriweather_24pt_SemiCondensed-ExtraBoldItalic.ttf',
            'Merriweather_24pt_SemiCondensed-Italic.ttf',
            'Merriweather_24pt_SemiCondensed-Light.ttf',
            'Merriweather_24pt_SemiCondensed-LightItalic.ttf',
            'Merriweather_24pt_SemiCondensed-Medium.ttf',
            'Merriweather_24pt_SemiCondensed-MediumItalic.ttf',
            'Merriweather_24pt_SemiCondensed-Regular.ttf',
            'Merriweather_24pt_SemiCondensed-SemiBold.ttf',
            'Merriweather_24pt_SemiCondensed-SemiBoldItalic.ttf',
            'Merriweather_24pt-Black.ttf',
            'Merriweather_24pt-BlackItalic.ttf',
            'Merriweather_24pt-Bold.ttf',
            'Merriweather_24pt-BoldItalic.ttf',
            'Merriweather_24pt-ExtraBold.ttf',
            'Merriweather_24pt-ExtraBoldItalic.ttf',
            'Merriweather_24pt-Italic.ttf',
            'Merriweather_24pt-Light.ttf',
            'Merriweather_24pt-LightItalic.ttf',
            'Merriweather_24pt-Medium.ttf',
            'Merriweather_24pt-MediumItalic.ttf',
            'Merriweather_24pt-Regular.ttf',
            'Merriweather_24pt-SemiBold.ttf',
            'Merriweather_24pt-SemiBoldItalic.ttf',
            'Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf',
            'Merriweather-VariableFont_opsz,wdth,wght.ttf',
            'Montserrat-Black.ttf',
            'Montserrat-BlackItalic.ttf',
            'Montserrat-Bold.ttf',
            'Montserrat-BoldItalic.ttf',
            'Montserrat-ExtraBold.ttf',
            'Montserrat-ExtraBoldItalic.ttf',
            'Montserrat-ExtraLight.ttf',
            'Montserrat-ExtraLightItalic.ttf',
            'Montserrat-Italic-VariableFont_wght.ttf',
            'Montserrat-Italic.ttf',
            'Montserrat-Light.ttf',
            'Montserrat-LightItalic.ttf',
            'Montserrat-Medium.ttf',
            'Montserrat-MediumItalic.ttf',
            'Montserrat-Regular.ttf',
            'Montserrat-SemiBold.ttf',
            'Montserrat-SemiBoldItalic.ttf',
            'Montserrat-Thin.ttf',
            'Montserrat-ThinItalic.ttf',
            'Montserrat-VariableFont_wght.ttf',
          ]
# 'NotoSans_Condensed-Black.ttf',
# 'NotoSans_Condensed-BlackItalic.ttf',
# 'NotoSans_Condensed-Bold.ttf',
# 'NotoSans_Condensed-BoldItalic.ttf',
# 'NotoSans_Condensed-ExtraBold.ttf',
# 'NotoSans_Condensed-ExtraBoldItalic.ttf',
# 'NotoSans_Condensed-ExtraLight.ttf',
# 'NotoSans_Condensed-ExtraLightItalic.ttf',
# 'NotoSans_Condensed-Italic.ttf',
# 'NotoSans_Condensed-Light.ttf',
# 'NotoSans_Condensed-LightItalic.ttf',
# 'NotoSans_Condensed-Medium.ttf',
# 'NotoSans_Condensed-MediumItalic.ttf',
# 'NotoSans_Condensed-Regular.ttf',
# 'NotoSans_Condensed-SemiBold.ttf',
# 'NotoSans_Condensed-SemiBoldItalic.ttf',
# 'NotoSans_Condensed-Thin.ttf',
# 'NotoSans_Condensed-ThinItalic.ttf',
# 'NotoSans_ExtraCondensed-Black.ttf',
# 'NotoSans_ExtraCondensed-BlackItalic.ttf',
# 'NotoSans_ExtraCondensed-Bold.ttf',
# 'NotoSans_ExtraCondensed-BoldItalic.ttf',
# 'NotoSans_ExtraCondensed-ExtraBold.ttf',
# 'NotoSans_ExtraCondensed-ExtraBoldItalic.ttf',
# 'NotoSans_ExtraCondensed-ExtraLight.ttf',
# 'NotoSans_ExtraCondensed-ExtraLightItalic.ttf',
# 'NotoSans_ExtraCondensed-Italic.ttf',
# 'NotoSans_ExtraCondensed-Light.ttf',
# 'NotoSans_ExtraCondensed-LightItalic.ttf',
# 'NotoSans_ExtraCondensed-Medium.ttf',
# 'NotoSans_ExtraCondensed-MediumItalic.ttf',
# 'NotoSans_ExtraCondensed-Regular.ttf',
# 'NotoSans_ExtraCondensed-SemiBold.ttf',
# 'NotoSans_ExtraCondensed-SemiBoldItalic.ttf',
# 'NotoSans_ExtraCondensed-Thin.ttf',
# 'NotoSans_ExtraCondensed-ThinItalic.ttf',
# 'NotoSans_SemiCondensed-Black.ttf',
# 'NotoSans_SemiCondensed-BlackItalic.ttf',
# 'NotoSans_SemiCondensed-Bold.ttf',
# 'NotoSans_SemiCondensed-BoldItalic.ttf',
# 'NotoSans_SemiCondensed-ExtraBold.ttf',
# 'NotoSans_SemiCondensed-ExtraBoldItalic.ttf',
# 'NotoSans_SemiCondensed-ExtraLight.ttf',
# 'NotoSans_SemiCondensed-ExtraLightItalic.ttf',
# 'NotoSans_SemiCondensed-Italic.ttf',
# 'NotoSans_SemiCondensed-Light.ttf',
# 'NotoSans_SemiCondensed-LightItalic.ttf',
# 'NotoSans_SemiCondensed-Medium.ttf',
# 'NotoSans_SemiCondensed-MediumItalic.ttf',
# 'NotoSans_SemiCondensed-Regular.ttf',
# 'NotoSans_SemiCondensed-SemiBold.ttf',
# 'NotoSans_SemiCondensed-SemiBoldItalic.ttf',
# 'NotoSans_SemiCondensed-Thin.ttf',
# 'NotoSans_SemiCondensed-ThinItalic.ttf',
# 'NotoSans-Black.ttf',
# 'NotoSans-BlackItalic.ttf',
# 'NotoSans-Bold.ttf',
# 'NotoSans-BoldItalic.ttf',
# 'NotoSans-ExtraBold.ttf',
# 'NotoSans-ExtraBoldItalic.ttf',
# 'NotoSans-ExtraLight.ttf',
# 'NotoSans-ExtraLightItalic.ttf',
# 'NotoSans-Italic-VariableFont_wdth,wght.ttf',
# 'NotoSans-Italic.ttf',
# 'NotoSans-Light.ttf',
# 'NotoSans-LightItalic.ttf',
# 'NotoSans-Medium.ttf',
# 'NotoSans-MediumItalic.ttf',
# 'NotoSans-Regular.ttf',
# 'NotoSans-SemiBold.ttf',
# 'NotoSans-SemiBoldItalic.ttf',
# 'NotoSans-Thin.ttf',
# 'NotoSans-ThinItalic.ttf',
# 'NotoSans-VariableFont_wdth,wght.ttf',
# 'NotoSerif_Condensed-Black.ttf',
# 'NotoSerif_Condensed-BlackItalic.ttf',
# 'NotoSerif_Condensed-Bold.ttf',
# 'NotoSerif_Condensed-BoldItalic.ttf',
# 'NotoSerif_Condensed-ExtraBold.ttf',
# 'NotoSerif_Condensed-ExtraBoldItalic.ttf',
# 'NotoSerif_Condensed-ExtraLight.ttf',
# 'NotoSerif_Condensed-ExtraLightItalic.ttf',
# 'NotoSerif_Condensed-Italic.ttf',
# 'NotoSerif_Condensed-Light.ttf',
# 'NotoSerif_Condensed-LightItalic.ttf',
# 'NotoSerif_Condensed-Medium.ttf',
# 'NotoSerif_Condensed-MediumItalic.ttf',
# 'NotoSerif_Condensed-Regular.ttf',
# 'NotoSerif_Condensed-SemiBold.ttf',
# 'NotoSerif_Condensed-SemiBoldItalic.ttf',
# 'NotoSerif_Condensed-Thin.ttf',
# 'NotoSerif_Condensed-ThinItalic.ttf',
# 'NotoSerif_ExtraCondensed-Black.ttf',
# 'NotoSerif_ExtraCondensed-BlackItalic.ttf',
# 'NotoSerif_ExtraCondensed-Bold.ttf',
# 'NotoSerif_ExtraCondensed-BoldItalic.ttf',
# 'NotoSerif_ExtraCondensed-ExtraBold.ttf',
# 'NotoSerif_ExtraCondensed-ExtraBoldItalic.ttf',
# 'NotoSerif_ExtraCondensed-ExtraLight.ttf',
# 'NotoSerif_ExtraCondensed-ExtraLightItalic.ttf',
# 'NotoSerif_ExtraCondensed-Italic.ttf',
# 'NotoSerif_ExtraCondensed-Light.ttf',
# 'NotoSerif_ExtraCondensed-LightItalic.ttf',
# 'NotoSerif_ExtraCondensed-Medium.ttf',
# 'NotoSerif_ExtraCondensed-MediumItalic.ttf',
# 'NotoSerif_ExtraCondensed-Regular.ttf',
# 'NotoSerif_ExtraCondensed-SemiBold.ttf',
# 'NotoSerif_ExtraCondensed-SemiBoldItalic.ttf',
# 'NotoSerif_ExtraCondensed-Thin.ttf',
# 'NotoSerif_ExtraCondensed-ThinItalic.ttf',
# 'NotoSerif_SemiCondensed-Black.ttf',
# 'NotoSerif_SemiCondensed-BlackItalic.ttf',
# 'NotoSerif_SemiCondensed-Bold.ttf',
# 'NotoSerif_SemiCondensed-BoldItalic.ttf',
# 'NotoSerif_SemiCondensed-ExtraBold.ttf',
# 'NotoSerif_SemiCondensed-ExtraBoldItalic.ttf',
# 'NotoSerif_SemiCondensed-ExtraLight.ttf',
# 'NotoSerif_SemiCondensed-ExtraLightItalic.ttf',
# 'NotoSerif_SemiCondensed-Italic.ttf',
# 'NotoSerif_SemiCondensed-Light.ttf',
# 'NotoSerif_SemiCondensed-LightItalic.ttf',
# 'NotoSerif_SemiCondensed-Medium.ttf',
# 'NotoSerif_SemiCondensed-MediumItalic.ttf',
# 'NotoSerif_SemiCondensed-Regular.ttf',
# 'NotoSerif_SemiCondensed-SemiBold.ttf',
# 'NotoSerif_SemiCondensed-SemiBoldItalic.ttf',
# 'NotoSerif_SemiCondensed-Thin.ttf',
# 'NotoSerif_SemiCondensed-ThinItalic.ttf',
# 'NotoSerif-Black.ttf',
# 'NotoSerif-BlackItalic.ttf',
# 'NotoSerif-Bold.ttf',
# 'NotoSerif-BoldItalic.ttf',
# 'NotoSerif-ExtraBold.ttf',
# 'NotoSerif-ExtraBoldItalic.ttf',
# 'NotoSerif-ExtraLight.ttf',
# 'NotoSerif-ExtraLightItalic.ttf',
# 'NotoSerif-Italic-VariableFont_wdth,wght.ttf',
# 'NotoSerif-Italic.ttf',
# 'NotoSerif-Light.ttf',
# 'NotoSerif-LightItalic.ttf',
# 'NotoSerif-Medium.ttf',
# 'NotoSerif-MediumItalic.ttf',
# 'NotoSerif-Regular.ttf',
# 'NotoSerif-SemiBold.ttf',
# 'NotoSerif-SemiBoldItalic.ttf',
# 'NotoSerif-Thin.ttf',
# 'NotoSerif-ThinItalic.ttf',
# 'NotoSerif-VariableFont_wdth,wght.ttf',
# 'Nunito-Black.ttf',
# 'Nunito-BlackItalic.ttf',
# 'Nunito-Bold.ttf',
# 'Nunito-BoldItalic.ttf',
# 'Nunito-ExtraBold.ttf',
# 'Nunito-ExtraBoldItalic.ttf',
# 'Nunito-ExtraLight.ttf',
# 'Nunito-ExtraLightItalic.ttf',
# 'Nunito-Italic-VariableFont_wght.ttf',
# 'Nunito-Italic.ttf',
# 'Nunito-Light.ttf',
# 'Nunito-LightItalic.ttf',
# 'Nunito-Medium.ttf',
# 'Nunito-MediumItalic.ttf',
# 'Nunito-Regular.ttf',
# 'Nunito-SemiBold.ttf',
# 'Nunito-SemiBoldItalic.ttf',
# 'Nunito-VariableFont_wght.ttf',
# 'NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf',
# 'NunitoSans-VariableFont_YTLC,opsz,wdth,wght.ttf',
# 'OpenSans_Condensed-Bold.ttf',
# 'OpenSans_Condensed-BoldItalic.ttf',
# 'OpenSans_Condensed-ExtraBold.ttf',
# 'OpenSans_Condensed-ExtraBoldItalic.ttf',
# 'OpenSans_Condensed-Italic.ttf',
# 'OpenSans_Condensed-Light.ttf',
# 'OpenSans_Condensed-LightItalic.ttf',
# 'OpenSans_Condensed-Medium.ttf',
# 'OpenSans_Condensed-MediumItalic.ttf',
# 'OpenSans_Condensed-Regular.ttf',
# 'OpenSans_Condensed-SemiBold.ttf',
# 'OpenSans_Condensed-SemiBoldItalic.ttf',
# 'OpenSans_SemiCondensed-Bold.ttf',
# 'OpenSans_SemiCondensed-BoldItalic.ttf',
# 'OpenSans_SemiCondensed-ExtraBold.ttf',
# 'OpenSans_SemiCondensed-ExtraBoldItalic.ttf',
# 'OpenSans_SemiCondensed-Italic.ttf',
# 'OpenSans_SemiCondensed-Light.ttf',
# 'OpenSans_SemiCondensed-LightItalic.ttf',
# 'OpenSans_SemiCondensed-Medium.ttf',
# 'OpenSans_SemiCondensed-MediumItalic.ttf',
# 'OpenSans_SemiCondensed-Regular.ttf',
# 'OpenSans_SemiCondensed-SemiBold.ttf',
# 'OpenSans_SemiCondensed-SemiBoldItalic.ttf',
# 'OpenSans-Bold.ttf',
# 'OpenSans-BoldItalic.ttf',
# 'OpenSans-ExtraBold.ttf',
# 'OpenSans-ExtraBoldItalic.ttf',
# 'OpenSans-Italic-VariableFont_wdth,wght.ttf',
# 'OpenSans-Italic.ttf',
# 'OpenSans-Light.ttf',
# 'OpenSans-LightItalic.ttf',
# 'OpenSans-Medium.ttf',
# 'OpenSans-MediumItalic.ttf',
# 'OpenSans-Regular.ttf',
# 'OpenSans-SemiBold.ttf',
# 'OpenSans-SemiBoldItalic.ttf',
# 'OpenSans-VariableFont_wdth,wght.ttf',
# 'Oswald-Bold.ttf',
# 'Oswald-ExtraLight.ttf',
# 'Oswald-Light.ttf',
# 'Oswald-Medium.ttf',
# 'Oswald-Regular.ttf',
# 'Oswald-SemiBold.ttf',
# 'Oswald-VariableFont_wght.ttf',
# 'PlayfairDisplay-Black.ttf',
# 'PlayfairDisplay-BlackItalic.ttf',
# 'PlayfairDisplay-Bold.ttf',
# 'PlayfairDisplay-BoldItalic.ttf',
# 'PlayfairDisplay-ExtraBold.ttf',
# 'PlayfairDisplay-ExtraBoldItalic.ttf',
# 'PlayfairDisplay-Italic-VariableFont_wght.ttf',
# 'PlayfairDisplay-Italic.ttf',
# 'PlayfairDisplay-Medium.ttf',
# 'PlayfairDisplay-MediumItalic.ttf',
# 'PlayfairDisplay-Regular.ttf',
# 'PlayfairDisplay-SemiBold.ttf',
# 'PlayfairDisplay-SemiBoldItalic.ttf',
# 'PlayfairDisplay-VariableFont_wght.ttf',
# 'Poppins-Black.ttf',
# 'Poppins-BlackItalic.ttf',
# 'Poppins-Bold.ttf',
# 'Poppins-BoldItalic.ttf',
# 'Poppins-ExtraBold.ttf',
# 'Poppins-ExtraBoldItalic.ttf',
# 'Poppins-ExtraLight.ttf',
# 'Poppins-ExtraLightItalic.ttf',
# 'Poppins-Italic.ttf',
# 'Poppins-Light.ttf',
# 'Poppins-LightItalic.ttf',
# 'Poppins-Medium.ttf',
# 'Poppins-MediumItalic.ttf',
# 'Poppins-Regular.ttf',
# 'Poppins-SemiBold.ttf',
# 'Poppins-SemiBoldItalic.ttf',
# 'Poppins-Thin.ttf',
# 'Poppins-ThinItalic.ttf',
# 'PTSerif-Bold.ttf',
# 'PTSerif-BoldItalic.ttf',
# 'PTSerif-Italic.ttf',
# 'PTSerif-Regular.ttf',
# 'Raleway-Black.ttf',
# 'Raleway-BlackItalic.ttf',
# 'Raleway-Bold.ttf',
# 'Raleway-BoldItalic.ttf',
# 'Raleway-ExtraBold.ttf',
# 'Raleway-ExtraBoldItalic.ttf',
# 'Raleway-ExtraLight.ttf',
# 'Raleway-ExtraLightItalic.ttf',
# 'Raleway-Italic-VariableFont_wght.ttf',
# 'Raleway-Italic.ttf',
# 'Raleway-Light.ttf',
# 'Raleway-LightItalic.ttf',
# 'Raleway-Medium.ttf',
# 'Raleway-MediumItalic.ttf',
# 'Raleway-Regular.ttf',
# 'Raleway-SemiBold.ttf',
# 'Raleway-SemiBoldItalic.ttf',
# 'Raleway-Thin.ttf',
# 'Raleway-ThinItalic.ttf',
# 'Raleway-VariableFont_wght.ttf',
# 'Roboto_Condensed-Black.ttf',
# 'Roboto_Condensed-BlackItalic.ttf',
# 'Roboto_Condensed-Bold.ttf',
# 'Roboto_Condensed-BoldItalic.ttf',
# 'Roboto_Condensed-ExtraBold.ttf',
# 'Roboto_Condensed-ExtraBoldItalic.ttf',
# 'Roboto_Condensed-ExtraLight.ttf',
# 'Roboto_Condensed-ExtraLightItalic.ttf',
# 'Roboto_Condensed-Italic.ttf',
# 'Roboto_Condensed-Light.ttf',
# 'Roboto_Condensed-LightItalic.ttf',
# 'Roboto_Condensed-Medium.ttf',
# 'Roboto_Condensed-MediumItalic.ttf',
# 'Roboto_Condensed-Regular.ttf',
# 'Roboto_Condensed-SemiBold.ttf',
# 'Roboto_Condensed-SemiBoldItalic.ttf',
# 'Roboto_Condensed-Thin.ttf',
# 'Roboto_Condensed-ThinItalic.ttf',
# 'Roboto_SemiCondensed-Black.ttf',
# 'Roboto_SemiCondensed-BlackItalic.ttf',
# 'Roboto_SemiCondensed-Bold.ttf',
# 'Roboto_SemiCondensed-BoldItalic.ttf',
# 'Roboto_SemiCondensed-ExtraBold.ttf',
# 'Roboto_SemiCondensed-ExtraBoldItalic.ttf',
# 'Roboto_SemiCondensed-ExtraLight.ttf',
# 'Roboto_SemiCondensed-ExtraLightItalic.ttf',
# 'Roboto_SemiCondensed-Italic.ttf',
# 'Roboto_SemiCondensed-Light.ttf',
# 'Roboto_SemiCondensed-LightItalic.ttf',
# 'Roboto_SemiCondensed-Medium.ttf',
# 'Roboto_SemiCondensed-MediumItalic.ttf',
# 'Roboto_SemiCondensed-Regular.ttf',
# 'Roboto_SemiCondensed-SemiBold.ttf',
# 'Roboto_SemiCondensed-SemiBoldItalic.ttf',
# 'Roboto_SemiCondensed-Thin.ttf',
# 'Roboto_SemiCondensed-ThinItalic.ttf',
# 'Roboto-Black.ttf',
# 'Roboto-BlackItalic.ttf',
# 'Roboto-Bold.ttf',
# 'Roboto-BoldItalic.ttf',
# 'Roboto-ExtraBold.ttf',
# 'Roboto-ExtraBoldItalic.ttf',
# 'Roboto-ExtraLight.ttf',
# 'Roboto-ExtraLightItalic.ttf',
# 'Roboto-Italic-VariableFont_wdth,wght.ttf',
# 'Roboto-Italic.ttf',
# 'Roboto-Light.ttf',
# 'Roboto-LightItalic.ttf',
# 'Roboto-Medium.ttf',
# 'Roboto-MediumItalic.ttf',
# 'Roboto-Regular.ttf',
# 'Roboto-SemiBold.ttf',
# 'Roboto-SemiBoldItalic.ttf',
# 'Roboto-Thin.ttf',
# 'Roboto-ThinItalic.ttf',
# 'Roboto-VariableFont_wdth,wght.ttf',
# 'RobotoMono-Bold.ttf',
# 'RobotoMono-BoldItalic.ttf',
# 'RobotoMono-ExtraLight.ttf',
# 'RobotoMono-ExtraLightItalic.ttf',
# 'RobotoMono-Italic-VariableFont_wght.ttf',
# 'RobotoMono-Italic.ttf',
# 'RobotoMono-Light.ttf',
# 'RobotoMono-LightItalic.ttf',
# 'RobotoMono-Medium.ttf',
# 'RobotoMono-MediumItalic.ttf',
# 'RobotoMono-Regular.ttf',
# 'RobotoMono-SemiBold.ttf',
# 'RobotoMono-SemiBoldItalic.ttf',
# 'RobotoMono-Thin.ttf',
# 'RobotoMono-ThinItalic.ttf',
# 'RobotoMono-VariableFont_wght.ttf',
# 'RobotoSlab-Black.ttf',
# 'RobotoSlab-Bold.ttf',
# 'RobotoSlab-ExtraBold.ttf',
# 'RobotoSlab-ExtraLight.ttf',
# 'RobotoSlab-Light.ttf',
# 'RobotoSlab-Medium.ttf',
# 'RobotoSlab-Regular.ttf',
# 'RobotoSlab-SemiBold.ttf',
# 'RobotoSlab-Thin.ttf',
# 'RobotoSlab-VariableFont_wght.ttf',
# 'Rubik-Black.ttf',
# 'Rubik-BlackItalic.ttf',
# 'Rubik-Bold.ttf',
# 'Rubik-BoldItalic.ttf',
# 'Rubik-ExtraBold.ttf',
# 'Rubik-ExtraBoldItalic.ttf',
# 'Rubik-Italic-VariableFont_wght.ttf',
# 'Rubik-Italic.ttf',
# 'Rubik-Light.ttf',
# 'Rubik-LightItalic.ttf',
# 'Rubik-Medium.ttf',
# 'Rubik-MediumItalic.ttf',
# 'Rubik-Regular.ttf',
# 'Rubik-SemiBold.ttf',
# 'Rubik-SemiBoldItalic.ttf',
# 'Rubik-VariableFont_wght.ttf',
# 'Slabo27px-Regular.ttf',
# 'Ubuntu-Bold.ttf',
# 'Ubuntu-BoldItalic.ttf',
# 'Ubuntu-Italic.ttf',
# 'Ubuntu-Light.ttf',
# 'Ubuntu-LightItalic.ttf',
# 'Ubuntu-Medium.ttf',
# 'Ubuntu-MediumItalic.ttf',
# 'Ubuntu-Regular.ttf',
      language: en
